# Generated by Django 4.2.5 on 2023-09-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Doctor Name')),
                ('gender', models.CharField(choices=[('other', 'Other'), ('female', 'Female'), ('male', 'Male')], verbose_name='Gender')),
                ('phone', models.CharField(verbose_name='Phone')),
                ('address', models.CharField(verbose_name='Address')),
                ('street', models.CharField(verbose_name='Street')),
                ('country', models.CharField(verbose_name='Country')),
                ('photo', models.ImageField(upload_to='doctor_profile')),
                ('doctor_type', models.CharField(choices=[('internal_medicine_physician', 'Internal Medicine Physician'), ('dermatologist', 'Dermatologist'), ('cardiologist', 'Cardiologist'), ('allergist_immunologist', 'Allergist/Immunologist'), ('pediatrician', 'Pediatrician'), ('family_practice_physician', 'Family Practice Physician'), ('geriatrician', 'Geriatric Medicine Doctor (Geriatrician)'), ('obstetrician_gynecologist', 'Obstetrician/Gynecologist (OB/GYN)'), ('infectious_disease_doctor', 'Infectious Disease Doctor'), ('ophthalmologist', 'Ophthalmologist')], verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Drug Name')),
                ('image', models.ImageField(upload_to='drug_profile/')),
                ('price', models.FloatField(verbose_name='Price')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('condition_treated', models.CharField(max_length=100, verbose_name='Condition Treated')),
                ('previous_price', models.FloatField(verbose_name='Previous price')),
                ('drug_type', models.CharField(choices=[('Spray', 'Spray'), ('Suspension', 'Suspension'), ('Suppository', 'Suppository'), ('Cream', 'Cream'), ('Lozenge', 'Lozenge'), ('Injection', 'Injection'), ('Tablet', 'Tablet'), ('Lotion', 'Lotion'), ('Chewable Tablet', 'Chewable Tablet'), ('Patch', 'Patch'), ('Capsule', 'Capsule'), ('Powder', 'Powder'), ('Gel', 'Gel'), ('Inhaler', 'Inhaler'), ('Ointment', 'Ointment'), ('Eye Drops', 'Eye Drops'), ('Syrup', 'Syrup'), ('Effervescent Tablet', 'Effervescent Tablet'), ('Nasal Spray', 'Nasal Spray'), ('Drops', 'Drops')], default='Tablet', verbose_name='Type')),
                ('drug_url', models.CharField(blank=True, verbose_name='Image url')),
            ],
        ),
        migrations.CreateModel(
            name='DrugManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Manufacturer Name')),
                ('phone', models.CharField(verbose_name='Phone')),
                ('Contact person', models.CharField()),
                ('address', models.CharField(verbose_name='Address')),
                ('street', models.CharField(verbose_name='Street')),
                ('country', models.CharField(verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Patient Name')),
                ('gender', models.CharField(choices=[('other', 'Other'), ('female', 'Female'), ('male', 'Male')], verbose_name='Gender')),
                ('phone', models.CharField(verbose_name='Phone')),
                ('address', models.CharField(verbose_name='Address')),
                ('street', models.CharField(verbose_name='Street')),
                ('country', models.CharField(verbose_name='Country')),
                ('photo', models.ImageField(upload_to='patient_profile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserID')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Pharmacy Name')),
                ('phone', models.CharField(verbose_name='Phone')),
                ('address', models.CharField(verbose_name='Address')),
                ('street', models.CharField(verbose_name='Street')),
                ('country', models.CharField(verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Prescription')),
                ('diagnosis', models.TextField(default='Only attended to by the doctor', verbose_name='Diagnosis')),
                ('dosage', models.CharField(default='Given with each drug', max_length=50, verbose_name='Dosage')),
                ('instructions', models.TextField(default='Adhere to instructions', verbose_name='Instructions')),
                ('state', models.CharField(choices=[('done', 'Done'), ('draft', 'Draft')], default='draft', verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Prescription Date')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.doctor', verbose_name='Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='prescriptionDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.TextField(default='5 mg', null=True, verbose_name='Dosage')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('drug_type', models.CharField(verbose_name='Medicine type')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='Drug Name')),
                ('flavors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.flavours', verbose_name='Flavour')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.prescription', verbose_name='Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Employee Name')),
                ('gender', models.CharField(choices=[('other', 'Other'), ('female', 'Female'), ('male', 'Male')], verbose_name='Gender')),
                ('phone', models.CharField(verbose_name='Phone')),
                ('address', models.CharField(verbose_name='Address')),
                ('street', models.CharField(verbose_name='Street')),
                ('country', models.CharField(verbose_name='Country')),
                ('photo', models.ImageField(upload_to='employee_profile')),
                ('Pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='flavour_id',
            field=models.ManyToManyField(to='pharmacy.flavours', verbose_name='Flavours'),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.ManyToManyField(to='pharmacy.drugmanufacturer', verbose_name='Manufacturer'),
        ),
    ]
