# Generated by Django 4.2.5 on 2023-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(choices=[('internal_medicine_physician', 'Internal Medicine Physician'), ('ophthalmologist', 'Ophthalmologist'), ('cardiologist', 'Cardiologist'), ('pediatrician', 'Pediatrician'), ('dermatologist', 'Dermatologist'), ('infectious_disease_doctor', 'Infectious Disease Doctor'), ('family_practice_physician', 'Family Practice Physician'), ('allergist_immunologist', 'Allergist/Immunologist'), ('geriatrician', 'Geriatric Medicine Doctor (Geriatrician)'), ('obstetrician_gynecologist', 'Obstetrician/Gynecologist (OB/GYN)')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('other', 'Other'), ('male', 'Male')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctor_profile'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(choices=[('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Eye Drops', 'Eye Drops'), ('Suppository', 'Suppository'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Nasal Spray', 'Nasal Spray'), ('Spray', 'Spray'), ('Gel', 'Gel'), ('Inhaler', 'Inhaler'), ('Suspension', 'Suspension'), ('Effervescent Tablet', 'Effervescent Tablet'), ('Capsule', 'Capsule'), ('Tablet', 'Tablet'), ('Lotion', 'Lotion'), ('Patch', 'Patch'), ('Powder', 'Powder'), ('Lozenge', 'Lozenge'), ('Chewable Tablet', 'Chewable Tablet'), ('Drops', 'Drops')], default='Tablet', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('other', 'Other'), ('male', 'Male')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('other', 'Other'), ('male', 'Male')], verbose_name='Gender'),
        ),
    ]
